# Clippy configuration for RONN project

# Complexity thresholds
cognitive-complexity-threshold = 25
type-complexity-threshold = 100

# Documentation requirements
missing-docs-in-crate-items = true

# Performance optimizations
avoid-breaking-exported-api = false

# Note: Specific lint allows/denies should be set via attributes in code:
# #[allow(clippy::todo)] or #![deny(clippy::panic)]
# The following lints are commonly allowed in this project:
# - clippy::todo (development phase)
# - clippy::missing_docs (internal types)
# - clippy::module_inception (clear organization)
# - clippy::large_enum_variant (comprehensive type systems)
# - clippy::type_complexity (ML operations)