# cargo-deny configuration for RONN security audits
# See: https://embarkstudios.github.io/cargo-deny/

[advisories]
# Check for security vulnerabilities in dependencies
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = []

[licenses]
# Allow common open source licenses
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]
deny = []
copyleft = "warn"
allow-osi-fsf-free = "both"
default = "deny"
confidence-threshold = 0.8

[bans]
# Ban certain crates or multiple versions
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
skip = []
skip-tree = []

[sources]
# Require all dependencies come from trusted sources
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
