# Edition and stability
edition = "2021"
unstable_features = false

# Line width and indentation
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports
reorder_imports = true
reorder_modules = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Functions and control flow
fn_params_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

# Comments and documentation
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80

# Formatting style
newline_style = "Unix"
remove_nested_parens = true
use_field_init_shorthand = true
use_try_shorthand = true

# String literals
format_strings = true

# Trailing elements
trailing_comma = "Vertical"
trailing_semicolon = true

# Spaces
spaces_around_ranges = false
type_punctuation_density = "Wide"